### ISSUE TITLE
Errores de consola

### ISSUE THREAD

**Issue by Nidev-lab** [NicolasViruel/Proyecto-Final#22]
## Proceso

1. Me loguee con un usuario.
2. Ingrese a "featured"
3. Hice click e intente añadir un producto a "favorites".

## Resultado esperado

Que al hacer click en enviar, el boton agregue el producto a favorites.

## Resultado actual

El boton no cumple su funcion y genera un error en la consola,.

## Captura

![image](https://user-images.githubusercontent.com/53904695/217936234-3ad53d49-67c5-4472-ac0b-90c35abbbba1.png)

Cualquier consulta pueden escribirme a nicogonzalez2008@gmail.com o por el slack de Rolling Code.

Saludos

**Comment by NicolasViruel** [comment]
Se creo una colección nueva para favoritos y ya funciona el agregado a "favoritos" desde el la pagina Featured, ademas se los puede eliminar.
