### ISSUE TITLE
Error de registro/consola

### ISSUE THREAD

**Issue by Nidev-lab** [NicolasViruel/Proyecto-Final#26]
## Proceso

1. Ingrese a sign up.
2. Ingrese mis datos y quise registrarme.

## Resultado esperado

Que al hacer click en "send", pueda registrarme e ingresar al sitio.

## Resultado actual

No me deja registrarme y genera un error en consola.

## Captura

imagen

<img width="868" alt="image" src="https://user-images.githubusercontent.com/53904695/222318327-aee2d56e-edce-40ab-bdfe-c4162c1cfb65.png">

**Comment by NicolasViruel** [comment]
Nicolás buenas dias!Listo ya verificamos que pudo haber pasado.Nicolás viruel Cel: +54 3813368181Argentina - Tucumán El 2 mar. 2023, a la(s) 00:18, Nico Gonzalez ***@***.***> escribió:﻿
Proceso

Ingrese a sign up.
Ingrese mis datos y quise registrarme.

Resultado esperado
Que al hacer click en "send", pueda registrarme e ingresar al sitio.
Resultado actual
No me deja registrarme y genera un error en consola.
Captura
imagen

**Comment by Nidev-lab** [comment]
Buenas Nicolas! al parecer el cambio no impacto

![image](https://user-images.githubusercontent.com/53904695/222856694-731a50e9-1549-4205-b865-8ad086d937b8.png)

**Comment by NicolasViruel** [comment]
Nicolas no te decía que ya lo íbamos a revisar al código, no lo
solucionamos aun!! estuvimos viendo y no encontramos aún el error al ser un
500, al parecer estamos pensando que viene desde el back.
Disculpame que no se entendio

**Comment by NicolasViruel** [comment]
Nicolas buenas tardes

Se soluciono el problema del registro y además se corrigieron algunos errores que encontramos.

Un saludo

**Comment by NicolasViruel** [comment]
Nicolas buenas tardes

¿Cómo estás?

Te quería comentar que ya solucionamos el error que teníamos al registrar
un nuevo usuario y cerramos el Issues, el equipo trabajó en conjunto y
además encontramos algunas cositas por modificar.
Paso a dejarte un Usuario Admin. para que tengas acceso.
*email:* ***@***.***
*password:* 123456Ab

Cualquier duda quedamos a disposición.

Saludos
